"""Changed DB Schema

Revision ID: 21fa1fa4447e
Revises: f7c391428f6b
Create Date: 2025-03-22 17:36:22.230963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fa1fa4447e'
down_revision: Union[str, None] = 'f7c391428f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_sessions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_sessions', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
