"""Changed DB Schema

Revision ID: 2fa426a54bdf
Revises: fc56edfd0af3
Create Date: 2025-03-23 01:25:07.056819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fa426a54bdf'
down_revision: Union[str, None] = 'fc56edfd0af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_sessions', sa.Column('user_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llm_sessions', sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('llm_sessions', 'conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_sessions', sa.Column('conversation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('llm_sessions', 'ai_response')
    op.drop_column('llm_sessions', 'user_input')
    # ### end Alembic commands ###
