"""Changed DB Schema

Revision ID: 3681d42adcf9
Revises: 2fa426a54bdf
Create Date: 2025-03-23 01:31:27.738153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3681d42adcf9'
down_revision: Union[str, None] = '2fa426a54bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_sessions', sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_sessions', 'chat_history')
    # ### end Alembic commands ###
