"""Changed DB Schema

Revision ID: ed579e91ea10
Revises: 8d2f56cb4504
Create Date: 2025-03-25 20:29:44.237669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed579e91ea10'
down_revision: Union[str, None] = '8d2f56cb4504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'base64',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'base64',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
