"""Changed DB Schema

Revision ID: f7c391428f6b
Revises: 4793d4fd2a13
Create Date: 2025-03-22 12:53:27.126832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c391428f6b'
down_revision: Union[str, None] = '4793d4fd2a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('llm_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('uploaded_files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('uploaded_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'updated_at')
    op.drop_column('uploaded_files', 'created_at')
    op.drop_column('llm_sessions', 'updated_at')
    op.drop_column('llm_sessions', 'created_at')
    # ### end Alembic commands ###
